backend:
  name: github
  repo: johnchourajr/john.design
  branch: master
  site_domain: elastic-payne-24cb37.netlify.com
media_folder: "journal/uploads"
publish_mode: editorial_workflow
collections:
  - name: "journal"
    label: "Journal"
    folder: "_journal"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: Layout, name: layout, widget: hidden, default: post}
      - {label: Title, name: title, widget: string}
      - {label: Cover Art, name: cover, widget: image}
      - {label: Tags, name: Tags, widget: list}
      - {label: Body, name: body, widget: markdown}
  - label: "Pages"
    name: "pages"
    files:
      - label: "Info"
        name: "info"
        file: "index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Header, name: header, widget: select, default: white, options: [white, black]}
          - {label: Layout, name: layout, widget: hidden, default: default}
          - {label: Layout, name: layout, widget: hidden, default: default}
          # - {label: Hello, name: hello, widget: markdown}
          # - {label: Work, name: work, widget: markdown}
          - label: Hello
            name: hello
            widget: object
            fields:
              - {label: Color, name: color, widget: string}
              - {label: Body, name: body, widget: markdown}
          - label: Work
            name: work
            widget: object
            fields:
              - {label: Color, name: color, widget: string}
              - {label: Body, name: body, widget: markdown}
          - label: Social
            name: social
            widget: object
            fields:
              - {label: Color, name: color, widget: string}
              - {label: Body, name: body, widget: markdown}
      - label: "Work"
        name: "work"
        file: "work/index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Header, name: header, widget: select, default: white, options: [white, black]}
          - {label: Layout, name: layout, widget: hidden, default: default}
          - {label: Headline, name: headline, widget: string}
          - label: Clients
            name: clients
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Role, name: role, widget: string}
              - {label: Link, name: link, widget: string}
              - {label: Year, name: year, widget: string}
              - {label: Image, name: img, widget: string}
              - {label: Data, name: data, widget: string}
          - label: Projects
            name: projects
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Description, name: description, widget: string}
              - {label: Link, name: link, widget: string}
              - {label: Year, name: year, widget: string}
              - {label: Image, name: img, widget: string}
              - {label: Data, name: data, widget: string}
      - label: "Journal"
        name: "journal"
        file: "journal/index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Header, name: header, widget: select, default: white, options: [white, black]}
          - {label: Layout, name: layout, widget: hidden, default: default}
          - {label: Headline, name: headline, widget: string}
          - {label: Top Section, name: top_section, widget: string}
      - label: "Credit"
        name: "credit"
        file: "credit/index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Header, name: header, widget: select, default: white, options: [white, black]}
          - {label: Layout, name: layout, widget: hidden, default: default}
          - {label: Headline, name: headline, widget: string}
          - {label: Technical, name: technical, widget: list}
          - {label: Other, name: other, widget: list}
      - label: "404"
        name: "404"
        file: "404.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Header, name: header, widget: select, default: white, options: [white, black]}
          - {label: Layout, name: layout, widget: hidden, default: 404}
          - {label: Headline, name: headline, widget: string}
          - {label: Subhead, name: subhead, widget: string}
          - {label: Note, name: note, widget: markdown}
