import React from "react";
import Head from "next/head";
import { motion, useScroll, useTransform } from "framer-motion";

const EXAMPLE_LIST = [{}, {}, {}, {}, {}];

function Section() {
  const ref = React.useRef(null);
  const { scrollYProgress } = useScroll({
    target: ref,
    offset: ["start 50%", "end"],
  });

  return (
    <section ref={ref} className="relative flex h-[300vh] ">
      <div className="sticky top-0 w-full h-[100vh]">
        {EXAMPLE_LIST.map((_, i) => (
          <Item key={i} index={i} scrollYProgress={scrollYProgress} />
        ))}
      </div>
    </section>
  );
}

function Item({ index, scrollYProgress }: any) {
  const key = () => {
    const offset = 1 / (EXAMPLE_LIST.length + 1);
    const segment = 1.5 / EXAMPLE_LIST.length;
    const start = index === 0 ? 0 : index * offset;
    const end = index + 1 === EXAMPLE_LIST.length ? 1 : start + segment;
    const middle = (start + end) / 2;
    const firstQuarter = (start + middle) / 2;
    const thirdQuarter = (middle + end) / 2;

    return {
      offset,
      segment,
      start,
      middle,
      firstQuarter,
      thirdQuarter,
      end,
    };
  };

  const keyframes = [
    key().start,
    key().firstQuarter,
    key().middle,
    key().thirdQuarter,
    key().end,
  ];

  const height = useTransform(scrollYProgress, keyframes, [
    "10%",
    "10%",
    "40%",
    "40%",
    "100%",
  ]);
  const width = useTransform(scrollYProgress, keyframes, [
    "10%",
    "10%",
    "24%",
    "24%",
    "66%",
  ]);
  const bottom = useTransform(scrollYProgress, keyframes, [
    "40%",
    "40%",
    "0%",
    "0%",
    "0%",
  ]);
  const right = useTransform(scrollYProgress, keyframes, [
    "0%",
    "0%",
    "10%",
    "10%",
    "34%",
  ]);

  const zIndex = useTransform(scrollYProgress, keyframes, [
    -index + 10,
    -index + 10,
    -index + 10,
    index + 10,
    index + 10,
  ]);

  return (
    <motion.div
      className="absolute w-full h-[100vh] flex justify-center items-center "
      style={{ zIndex }}
    >
      <motion.figure
        className="bg-red-600 absolute"
        style={{ width, height, right, bottom }}
      >
        {index}
        <svg className="absolute w-full h-full inset-0">
          <rect
            width="100%"
            height="100%"
            fill="transparent"
            stroke="black"
            strokeWidth={8}
          />
        </svg>
      </motion.figure>
    </motion.div>
  );
}

export default function Home() {
  return (
    <div className="relative w-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="relative flex items-center justify-start just min-h-[50vh]">
        Start scrolling down
      </section>
      <Section />
      <section className="relative flex items-center justify-start just min-h-[50vh]">
        Scroll back up
      </section>
    </div>
  );
}
